#!/usr/bin/env bash

# TODO: Remove the services you don't need
python iceflix/main.py --Ice.Config=configs/main.config &
python iceflix/catalog.py --Ice.Config=configs/catalog.config &
python iceflix/authenticator.py --Ice.Config=configs/authenticator.config &
python iceflix/file_service.py --Ice.Config=configs/fileservice.config
